#!/bin/bash
total 28
-rw-r--r-- 1 root root 12 Sep  5 14:39 5-firstlines
-rwxr--r-- 1 root root 29 Sep  5 14:30 4-lastlines
-rwxr--r-- 1 root root 39 Sep  5 14:19 3-twofiles
-rwxr--r-- 1 root root 28 Sep  5 14:03 2-hellofile
-rwxr--r-- 1 root root 28 Sep  5 13:59 1-confused_smiley
-rwxr--r-- 1 root root 30 Sep  5 13:06 0-hello_world
-rw-r--r-- 1 root root 33 Sep  5 05:30 README.md
