#!/usr/bin/env bash
# installing web servers

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a simple "Hello World!" HTML page
echo "<html><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
