#!/usr/bin/env bash
#this module makes the nginx run as nginx user
sudo sed -i 's/^user .*;$/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/^listen .*;$/listen 8080;/g' /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /var/lib/nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo service nginx start
