#!/usr/bin/env bash
"""
this module makes the nginx run as nginx user
"""

# Stop Nginx service if it's running
sudo service nginx stop

# Update the nginx configuration file
sudo sed -i 's/^user .*;$/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/^listen .*;$/listen 8080;/g' /etc/nginx/nginx.conf

# Update the ownership of Nginx directories
sudo chown -R nginx:nginx /var/lib/nginx
sudo chown -R nginx:nginx /var/log/nginx

# Start Nginx service
sudo service nginx start
