#!/bin/bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Stop Nginx service
sudo service nginx stop

# Change ownership of Nginx files and directories to nginx user
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx
sudo chown -R nginx:nginx /etc/nginx

# Modify Nginx configuration to run as nginx user
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Start Nginx service
sudo service nginx start

sudo sed -i 's/listen\s*\(.*\)\s*;/listen 8080;/g' /etc/nginx/nginx.conf

# Make Nginx listen on all active IPs on port 8080
sudo sed -i 's/listen 80;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Reload Nginx configuration
sudo service nginx reload
