#!/bin/bash

apt-get update
apt-get install -y nginx
service nginx stop
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/www/html /var/log/nginx
sed -i 's/listen 80;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
service nginx start
